from __future__ import annotations

import json
import os
import shutil
import sys
import uuid
from dataclasses import asdict, dataclass
from importlib.resources import files
from pathlib import Path
from typing import Iterable

from . import __version__


SKILL_NAME = "research-reading-contract"
SUPPORTED_AGENTS = ("codex", "claude")


@dataclass(frozen=True)
class InstallResult:
    agent: str
    destination: str
    version: str
    action: str


@dataclass(frozen=True)
class CheckResult:
    name: str
    ok: bool
    detail: str


def expand_agents(agent: str) -> list[str]:
    if agent == "both":
        return list(SUPPORTED_AGENTS)
    if agent not in SUPPORTED_AGENTS:
        raise ValueError(f"Unsupported agent: {agent}")
    return [agent]


def skill_destination(
    agent: str,
    *,
    scope: str,
    project_root: str | Path | None = None,
    home: str | Path | None = None,
) -> Path:
    if agent not in SUPPORTED_AGENTS:
        raise ValueError(f"Unsupported agent: {agent}")
    if scope not in {"user", "project"}:
        raise ValueError("scope must be user or project")

    if scope == "user":
        base = Path(home).expanduser() if home is not None else Path.home()
        skill_root = base / (".agents" if agent == "codex" else ".claude") / "skills"
    else:
        base = Path(project_root or Path.cwd()).expanduser().resolve()
        skill_root = base / (".agents" if agent == "codex" else ".claude") / "skills"
    return skill_root / SKILL_NAME


def _copy_resource_tree(source, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for child in source.iterdir():
        target = destination / child.name
        if child.is_dir():
            _copy_resource_tree(child, target)
        else:
            target.write_bytes(child.read_bytes())


def _runtime_markdown() -> str:
    executable = str(Path(sys.executable).resolve())
    if os.name == "nt":
        command = f'& "{executable}" -m research_reading_contract'
        shell = "PowerShell"
    else:
        command = f'"{executable}" -m research_reading_contract'
        shell = "POSIX shell"
    return (
        "# Local Runtime\n\n"
        "This file was generated by `rrc setup`. Do not publish it because it may "
        "contain a local filesystem path.\n\n"
        f"- Shell: {shell}\n"
        f"- `RRC_COMMAND`: `{command}`\n\n"
        "Use this exact command prefix for every RRC operation.\n"
    )


def _owned_install(destination: Path) -> bool:
    if destination.is_symlink():
        return False
    marker = destination / ".rrc-install.json"
    if not marker.is_file():
        return False
    try:
        metadata = json.loads(marker.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    return metadata.get("skill_name") == SKILL_NAME


def install_skills(
    agents: Iterable[str],
    *,
    scope: str = "user",
    project_root: str | Path | None = None,
    home: str | Path | None = None,
    force: bool = False,
) -> list[InstallResult]:
    bundle = files("research_reading_contract").joinpath("bundled_skill")
    results: list[InstallResult] = []

    for agent in agents:
        destination = skill_destination(
            agent, scope=scope, project_root=project_root, home=home
        )
        action = "installed"
        destination_present = destination.exists() or destination.is_symlink()
        if destination_present:
            if not _owned_install(destination) and not force:
                raise ValueError(
                    f"Refusing to replace unrecognized directory: {destination}. "
                    "Move it aside or rerun with --force."
                )
            action = "updated"

        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = destination.parent / f".{SKILL_NAME}.tmp-{uuid.uuid4().hex}"
        backup = destination.parent / f".{SKILL_NAME}.backup-{uuid.uuid4().hex}"
        try:
            _copy_resource_tree(bundle, temporary)
            references = temporary / "references"
            references.mkdir(parents=True, exist_ok=True)
            (references / "runtime.md").write_text(
                _runtime_markdown(), encoding="utf-8"
            )
            metadata = {
                "skill_name": SKILL_NAME,
                "version": __version__,
                "agent": agent,
                "scope": scope,
            }
            (temporary / ".rrc-install.json").write_text(
                json.dumps(metadata, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            if destination_present:
                destination.replace(backup)
            try:
                temporary.replace(destination)
            except Exception:
                if backup.exists() or backup.is_symlink():
                    backup.replace(destination)
                raise
        finally:
            if temporary.exists():
                shutil.rmtree(temporary)
            if destination.exists() or destination.is_symlink():
                if backup.is_symlink() or backup.is_file():
                    backup.unlink()
                elif backup.exists():
                    shutil.rmtree(backup)

        results.append(
            InstallResult(
                agent=agent,
                destination=str(destination),
                version=__version__,
                action=action,
            )
        )
    return results


def doctor_checks(
    agents: Iterable[str],
    *,
    scope: str = "user",
    project_root: str | Path | None = None,
    home: str | Path | None = None,
) -> list[CheckResult]:
    checks: list[CheckResult] = [
        CheckResult(
            name="python",
            ok=sys.version_info >= (3, 10),
            detail=f"{sys.version.split()[0]} at {Path(sys.executable).resolve()}",
        )
    ]
    try:
        import pypdf

        checks.append(CheckResult("pdf_backend", True, f"pypdf {pypdf.__version__}"))
    except ImportError:
        checks.append(CheckResult("pdf_backend", False, "pypdf is not installed"))

    for agent in agents:
        destination = skill_destination(
            agent, scope=scope, project_root=project_root, home=home
        )
        required = [
            destination / "SKILL.md",
            destination / "references" / "protocol.md",
            destination / "references" / "reading-report.schema.json",
            destination / "references" / "runtime.md",
            destination / ".rrc-install.json",
        ]
        missing = [path.name for path in required if not path.is_file()]
        installation_errors: list[str] = []
        if not missing:
            try:
                metadata = json.loads(
                    (destination / ".rrc-install.json").read_text(encoding="utf-8")
                )
            except (OSError, json.JSONDecodeError) as exc:
                installation_errors.append(f"invalid install metadata: {exc}")
            else:
                if metadata.get("version") != __version__:
                    installation_errors.append(
                        f"installed version {metadata.get('version')} != runtime {__version__}"
                    )
                if metadata.get("agent") != agent:
                    installation_errors.append("install metadata names a different agent")
            runtime_text = (destination / "references" / "runtime.md").read_text(
                encoding="utf-8"
            )
            if str(Path(sys.executable).resolve()) not in runtime_text:
                installation_errors.append("runtime.md does not point to this environment")

        skill_ok = not missing and not installation_errors
        checks.append(
            CheckResult(
                name=f"{agent}_skill",
                ok=skill_ok,
                detail=(
                    str(destination)
                    if skill_ok
                    else "; ".join(
                        ([f"missing {', '.join(missing)}"] if missing else [])
                        + installation_errors
                    )
                    + f" in {destination}"
                ),
            )
        )
        binary = shutil.which(agent)
        checks.append(
            CheckResult(
                name=f"{agent}_command",
                ok=binary is not None,
                detail=binary or f"{agent} command not found on PATH",
            )
        )
    return checks


def results_as_dict(results: Iterable[InstallResult]) -> list[dict[str, str]]:
    return [asdict(result) for result in results]


def checks_as_dict(checks: Iterable[CheckResult]) -> list[dict[str, object]]:
    return [asdict(check) for check in checks]
